create extension if not exists pgcrypto;

create table if not exists public.learner_profiles (
  conversation_id uuid primary key default gen_random_uuid(),
  level smallint not null default 4 check (level between 1 and 6),
  label text not null default 'CET-4 (B1-B2)',
  last_reason text not null default 'Default starting level',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.realtime_sessions (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.learner_profiles(conversation_id) on delete cascade,
  status text not null default 'active' check (status in ('active', 'closed', 'expired')),
  prompt text not null default '' check (char_length(prompt) <= 2000),
  client_hash text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '2 hours'),
  closed_at timestamptz
);

create index if not exists realtime_sessions_conversation_created_idx
  on public.realtime_sessions (conversation_id, created_at desc);
create index if not exists realtime_sessions_active_expiry_idx
  on public.realtime_sessions (expires_at) where status = 'active';

create table if not exists public.session_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.realtime_sessions(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  body text not null check (char_length(body) between 1 and 8000),
  source_id text not null check (char_length(source_id) <= 128),
  created_at timestamptz not null default now(),
  unique (session_id, role, source_id)
);

create index if not exists session_messages_session_created_idx
  on public.session_messages (session_id, created_at);

create table if not exists public.realtime_metrics (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.realtime_sessions(id) on delete cascade,
  metric_type text not null default 'client',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists realtime_metrics_session_created_idx
  on public.realtime_metrics (session_id, created_at desc);

create table if not exists public.request_rate_limits (
  id bigint generated by default as identity primary key,
  client_hash text not null,
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists request_rate_limits_lookup_idx
  on public.request_rate_limits (client_hash, action, created_at desc);

alter table public.learner_profiles enable row level security;
alter table public.realtime_sessions enable row level security;
alter table public.session_messages enable row level security;
alter table public.realtime_metrics enable row level security;
alter table public.request_rate_limits enable row level security;

revoke all on table public.learner_profiles from anon, authenticated;
revoke all on table public.realtime_sessions from anon, authenticated;
revoke all on table public.session_messages from anon, authenticated;
revoke all on table public.realtime_metrics from anon, authenticated;
revoke all on table public.request_rate_limits from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

comment on table public.realtime_sessions is 'Short-lived metadata for Web realtime coaching sessions; no audio is stored.';
comment on table public.session_messages is 'Final transcript messages only; raw audio is never persisted.';
